// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTemplate.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    [Migration("20251027162353_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTemplate.Models.Biblioteka", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Biblioteke");
                });

            modelBuilder.Entity("WebTemplate.Models.Polica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Oznaka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("maksimalnoKnjiga")
                        .HasColumnType("bigint");

                    b.Property<int>("policaBibliotekaID")
                        .HasColumnType("int");

                    b.Property<long>("trenutnoKnjiga")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("policaBibliotekaID");

                    b.ToTable("Police");
                });

            modelBuilder.Entity("WebTemplate.Models.Polica", b =>
                {
                    b.HasOne("WebTemplate.Models.Biblioteka", "policaBiblioteka")
                        .WithMany("police")
                        .HasForeignKey("policaBibliotekaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("policaBiblioteka");
                });

            modelBuilder.Entity("WebTemplate.Models.Biblioteka", b =>
                {
                    b.Navigation("police");
                });
#pragma warning restore 612, 618
        }
    }
}
